/* AUTOGENERATED FILE. DO NOT EDIT. */

#define DOING_UNIT_TESTS
/*=======Test Runner Used To Run Each Test Below=====*/
#define RUN_TEST(TestFunc, TestLineNum) \
{ \
  Unity.CurrentTestName = #TestFunc; \
  Unity.CurrentTestLineNumber = TestLineNum; \
  Unity.NumberOfTests++; \
  if (TEST_PROTECT()) \
  { \
      setUp(); \
      TestFunc(); \
  } \
  if (TEST_PROTECT()) \
  { \
    tearDown(); \
  } \
  UnityConcludeTest(); \
}

/*=======Automagically Detected Files To Include=====*/
#include "unity.h"
#include <setjmp.h>
#include <stdio.h>

/*=======External Functions This Runner Calls=====*/
extern void setUp(void);
extern void tearDown(void);

extern void TestingEncryptionXTEA_SUCESS(void);
extern void TestingDecryptionBLOWFISH256_FAILWrongType(void);
extern void TestingEncryptionBLOWFISH256_FAILWrongType(void);
extern void TestingDecryptionBLOWFISH256_FAILWrongInput(void);
extern void TestingEncryptionBLOWFISH256_FAILWrongInput(void);
extern void TestingDecryptionBLOWFISH256_FAILWrongKey(void);
extern void TestingEncryptionBLOWFISH256_FAILWrongKey(void);
extern void TestingDecryptionBLOWFISH192_FAILWrongType(void);
extern void TestingEncryptionBLOWFISH192_FAILWrongType(void);
extern void TestingDecryptionBLOWFISH192_FAILWrongInput(void);
extern void TestingEncryptionBLOWFISH192_FAILWrongInput(void);
extern void TestingDecryptionBLOWFISH192_FAILWrongKey(void);
extern void TestingEncryptionBLOWFISH192_FAILWrongKey(void);
extern void TestingDecryptionBLOWFISH128_FAILWrongType(void);
extern void TestingEncryptionBLOWFISH128_FAILWrongType(void);
extern void TestingDecryptionBLOWFISH128_FAILWrongInput(void);
extern void TestingEncryptionBLOWFISH128_FAILWrongInput(void);
extern void TestingDecryptionBLOWFISH128_FAILWrongKey(void);
extern void TestingEncryptionBLOWFISH128_FAILWrongKey(void);
extern void TestingDecryptionAES256_FAILWrongType(void);
extern void TestingEncryptionAES256_FAILWrongType(void);
extern void TestingDecryptionAES256_FAILWrongInput(void);
extern void TestingEncryptionAES256_FAILWrongInput(void);
extern void TestingDecryptionAES256_FAILWrongKey(void);
extern void TestingEncryptionAES256_FAILWrongKey(void);
extern void TestingDecryptionAES192_FAILWrongType(void);
extern void TestingEncryptionAES192_FAILWrongType(void);
extern void TestingDecryptionAES192_FAILWrongInput(void);
extern void TestingEncryptionAES192_FAILWrongInput(void);
extern void TestingDecryptionAES192_FAILWrongKey(void);
extern void TestingEncryptionAES192_FAILWrongKey(void);
extern void TestingDecryptionAES128_FAILWrongType(void);
extern void TestingEncryptionAES128_FAILWrongType(void);
extern void TestingDecryptionAES128_FAILWrongInput(void);
extern void TestingEncryptionAES128_FAILWrongInput(void);
extern void TestingDecryptionAES128_FAILWrongKey(void);
extern void TestingEncryptionAES128_FAILWrongKey(void);
extern void TestingDecryptionXTEA_FAILWrongType(void);
extern void TestingEncryptionXTEA_FAILWrongType(void);
extern void TestingDecryptionXTEA_FAILWrongInput(void);
extern void TestingEncryptionXTEA_FAILWrongInput(void);
extern void TestingDecryptionXTEA_FAILWrongKey(void);
extern void TestingEncryptionXTEA_FAILWrongKey(void);
extern void TestingEncryptionXTEA_FAILTypeDontExist_Float(void);
extern void TestingEncryptionBLOWFISH192_FAILEncDecDontExist_Float(void);
extern void TestingDecryptionAES192_FAILTypeDontExist_MenorQue0(void);
extern void TestingDecryptionAES256_FAILEncDecDontExist_MenorQue0(void);
extern void TestingEncryptionBLOWFISH256_FAILTypeDontExist_MaiorQue6(void);
extern void TestingEncryptionBLOWFISH128_FAILEncDecDontExist_MaiorQue1(void);
extern void TestingDecryptionBLOWFISH256_SUCESS(void);
extern void TestingDecryptionBLOWFISH192_SUCESS(void);
extern void TestingDecryptionBLOWFISH128_SUCESS(void);
extern void TestingDecryptionAES256_SUCESS(void);
extern void TestingDecryptionAES192_SUCESS(void);
extern void TestingDecryptionAES128_SUCESS(void);
extern void TestingDecryptionionXTEA_SUCESS(void);
extern void TestingEncryptionBLOWFISH256_SUCESS(void);
extern void TestingEncryptionBLOWFISH192_SUCESS(void);
extern void TestingEncryptionBLOWFISH128_SUCESS(void);
extern void TestingEncryptionAES256_SUCESS(void);
extern void TestingEncryptionAES192_SUCESS(void);
extern void TestingEncryptionAES128_SUCESS(void);
/*=======Test Reset Option=====*/
void resetTest(void);
void resetTest(void)
{
  tearDown();
  setUp();
}


/*=======MAIN=====*/
int main(void)
{
  UnityBegin("../crypt_test.c");

  RUN_TEST(TestingDecryptionBLOWFISH256_SUCESS, 12);
  RUN_TEST(TestingDecryptionBLOWFISH192_SUCESS, 12);
  RUN_TEST(TestingDecryptionBLOWFISH128_SUCESS, 12);
  RUN_TEST(TestingDecryptionAES256_SUCESS, 12);
  RUN_TEST(TestingDecryptionAES192_SUCESS, 12);
  RUN_TEST(TestingDecryptionAES128_SUCESS, 12);
  RUN_TEST(TestingDecryptionionXTEA_SUCESS, 12);
  RUN_TEST(TestingEncryptionBLOWFISH256_SUCESS, 12);
  RUN_TEST(TestingEncryptionBLOWFISH192_SUCESS, 12);
  RUN_TEST(TestingEncryptionBLOWFISH128_SUCESS, 12);
  RUN_TEST(TestingEncryptionAES256_SUCESS, 12);
  RUN_TEST(TestingEncryptionAES192_SUCESS, 12);
  RUN_TEST(TestingEncryptionAES128_SUCESS, 12);
  RUN_TEST(TestingEncryptionXTEA_SUCESS, 12);
  RUN_TEST(TestingEncryptionXTEA_FAILTypeDontExist_Float, 12);
  RUN_TEST(TestingEncryptionBLOWFISH192_FAILEncDecDontExist_Float, 12);
  RUN_TEST(TestingDecryptionAES192_FAILTypeDontExist_MenorQue0, 12);
  RUN_TEST(TestingDecryptionAES256_FAILEncDecDontExist_MenorQue0, 12);
  RUN_TEST(TestingEncryptionBLOWFISH256_FAILTypeDontExist_MaiorQue6, 12);
  RUN_TEST(TestingEncryptionBLOWFISH128_FAILEncDecDontExist_MaiorQue1, 12);
  RUN_TEST(TestingDecryptionBLOWFISH256_FAILWrongType, 12);
  RUN_TEST(TestingEncryptionBLOWFISH256_FAILWrongType, 12);
  RUN_TEST(TestingDecryptionBLOWFISH256_FAILWrongInput, 12);
  RUN_TEST(TestingEncryptionBLOWFISH256_FAILWrongInput, 12);
  RUN_TEST(TestingDecryptionBLOWFISH256_FAILWrongKey, 12);
  RUN_TEST(TestingEncryptionBLOWFISH256_FAILWrongKey, 12);
  RUN_TEST(TestingDecryptionBLOWFISH192_FAILWrongType, 12);
  RUN_TEST(TestingEncryptionBLOWFISH192_FAILWrongType, 12);
  RUN_TEST(TestingDecryptionBLOWFISH192_FAILWrongInput, 12);
  RUN_TEST(TestingEncryptionBLOWFISH192_FAILWrongInput, 12);
  RUN_TEST(TestingDecryptionBLOWFISH192_FAILWrongKey, 12);
  RUN_TEST(TestingEncryptionBLOWFISH192_FAILWrongKey, 12);
  RUN_TEST(TestingDecryptionBLOWFISH128_FAILWrongType, 12);
  RUN_TEST(TestingEncryptionBLOWFISH128_FAILWrongType, 12);
  RUN_TEST(TestingDecryptionBLOWFISH128_FAILWrongInput, 12);
  RUN_TEST(TestingEncryptionBLOWFISH128_FAILWrongInput, 12);
  RUN_TEST(TestingDecryptionBLOWFISH128_FAILWrongKey, 12);
  RUN_TEST(TestingEncryptionBLOWFISH128_FAILWrongKey, 12);
  RUN_TEST(TestingDecryptionAES256_FAILWrongType, 12);
  RUN_TEST(TestingEncryptionAES256_FAILWrongType, 12);
  RUN_TEST(TestingDecryptionAES256_FAILWrongInput, 12);
  RUN_TEST(TestingEncryptionAES256_FAILWrongInput, 12);
  RUN_TEST(TestingDecryptionAES256_FAILWrongKey, 12);
  RUN_TEST(TestingEncryptionAES256_FAILWrongKey, 12);
  RUN_TEST(TestingDecryptionAES192_FAILWrongType, 12);
  RUN_TEST(TestingEncryptionAES192_FAILWrongType, 12);
  RUN_TEST(TestingDecryptionAES192_FAILWrongInput, 12);
  RUN_TEST(TestingEncryptionAES192_FAILWrongInput, 12);
  RUN_TEST(TestingDecryptionAES192_FAILWrongKey, 12);
  RUN_TEST(TestingEncryptionAES192_FAILWrongKey, 12);
  RUN_TEST(TestingDecryptionAES128_FAILWrongType, 12);
  RUN_TEST(TestingEncryptionAES128_FAILWrongType, 12);
  RUN_TEST(TestingDecryptionAES128_FAILWrongInput, 12);
  RUN_TEST(TestingEncryptionAES128_FAILWrongInput, 12);
  RUN_TEST(TestingDecryptionAES128_FAILWrongKey, 12);
  RUN_TEST(TestingEncryptionAES128_FAILWrongKey, 12);
  RUN_TEST(TestingDecryptionXTEA_FAILWrongType, 12);
  RUN_TEST(TestingEncryptionXTEA_FAILWrongType, 12);
  RUN_TEST(TestingDecryptionXTEA_FAILWrongInput, 12);
  RUN_TEST(TestingEncryptionXTEA_FAILWrongInput, 12);
  RUN_TEST(TestingDecryptionXTEA_FAILWrongKey, 12);
  RUN_TEST(TestingEncryptionXTEA_FAILWrongKey, 12);
  RUN_TEST(TestingEncryptionXTEA_FAILTypeDontExist_Float, 12);
  RUN_TEST(TestingEncryptionBLOWFISH192_FAILEncDecDontExist_Float, 12);
  RUN_TEST(TestingDecryptionAES192_FAILTypeDontExist_MenorQue0, 12);
  RUN_TEST(TestingDecryptionAES256_FAILEncDecDontExist_MenorQue0, 12);
  RUN_TEST(TestingEncryptionBLOWFISH256_FAILTypeDontExist_MaiorQue6, 12);
  RUN_TEST(TestingEncryptionBLOWFISH128_FAILEncDecDontExist_MaiorQue1, 12);
  UnityEnd();
  //return (UnityEnd());
  return 0;
}